# **1. GPU 사용하는 방법**

In [2]:
import torch
import torch.nn as nn

In [3]:
x = torch.cuda.FloatTensor(2, 2) 
# 에러가 발생할 경우 런타임 -> 런타임 유형 변경에서 GPU를 선택
print(x)
# GPU가 여러개 있는 경우 GPU 번호를 확인
# 같은 디바이스에 있는 텐서끼리만 연산이 가능하다.

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')


In [4]:
x = torch.FloatTensor(2, 2)
print(x) # CPU(RAM) 사용 

tensor([[-7.5859e-29,  3.0862e-41],
        [ 3.3631e-44,  0.0000e+00]])


In [5]:
# GPU로 보냄
x.cuda()

tensor([[-7.5859e-29,  3.0862e-41],
        [ 3.3631e-44,  0.0000e+00]], device='cuda:0')

In [6]:
# GPU0으로 지정
d = torch.device('cuda:0')

In [7]:
# move가 아니라 copy로 됨
x.cuda(device=d)

tensor([[-7.5859e-29,  3.0862e-41],
        [ 3.3631e-44,  0.0000e+00]], device='cuda:0')

In [8]:
x.device
# x가 CPU에도 있고 GPU에서 copy되어 있음.

device(type='cpu')

# **2. Convert to CPU tensor from CUDA tensor**

In [9]:
x = torch.cuda.FloatTensor(2, 2)

In [10]:
x = x.cpu()

In [11]:
d = torch.device('cpu')
x = x.to(d) # CPU를 CUDA로 바꿈

# **3. Move model from CPU to GPU**

In [12]:
def print_params(model) :
  for p in model.parameters() :
    print(p)

In [15]:
linear = nn.Linear(2, 2)
# 기본 Linear
print_params(linear)

Parameter containing:
tensor([[ 0.4031, -0.6505],
        [-0.5398,  0.2415]], requires_grad=True)
Parameter containing:
tensor([ 0.5267, -0.4702], requires_grad=True)


In [16]:
linear = linear.cuda()
# 쿠다에서 Linear
print_params(linear)

Parameter containing:
tensor([[ 0.4031, -0.6505],
        [-0.5398,  0.2415]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([ 0.5267, -0.4702], device='cuda:0', requires_grad=True)


In [17]:
# 다시 CPU로 옮기기
linear = linear.cpu()
print_params(linear)

Parameter containing:
tensor([[ 0.4031, -0.6505],
        [-0.5398,  0.2415]], requires_grad=True)
Parameter containing:
tensor([ 0.5267, -0.4702], requires_grad=True)


In [18]:
# GPU 번호까지 정해서 CUDA 바꾸기
d = torch.device('cuda:0')
linear = linear.to(d)
print_params(linear)

Parameter containing:
tensor([[ 0.4031, -0.6505],
        [-0.5398,  0.2415]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([ 0.5267, -0.4702], device='cuda:0', requires_grad=True)


In [20]:
# linear.device # 모델은 device attribute 를 제공하지 않음

In [21]:
x = torch.cuda.FloatTensor(2, 2)

In [22]:
x.new(2, 2) # x와 같은 타입이면서 같은 디바이스에 있는 텐서를 만든다.

tensor([[0.0000, 1.7351],
        [0.5398, 0.2415]], device='cuda:0')

In [23]:
torch.zeros_like(x) # x와 같은 타입이면서 원소가 0이고 같은 디바이스에 만든다.

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [24]:
torch.ones_like(x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [26]:
list(linear.parameters())[0].new(2, 2)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

> 다른 device에 있는 텐서끼리는 연산할 수 없음